// ============================================================
// BIBLIOTECA DIGITAL — Datos de recursos
// Diseño: Archivo Nocturno — negro cálido + ámbar dorado
// ============================================================

export type ResourceType = "libro" | "podcast" | "audiolibro" | "documental" | "plataforma" | "youtube" | "curso";
export type Status = "en-cola" | "leyendo" | "completado";
export type NoteType = "aprendizaje" | "semilla" | "conexion";
export type PodcastTema = "mentalidad" | "dinero" | "negocios" | "marketing" | "espiritualidad" | "desarrollo-personal";

export type Note = {
  id: string;
  type: NoteType;
  content: string;
  createdAt: string;
};

export type Category = {
  id: string;
  name: string;
  numeral: string;
  color: string;
  note?: string;
};

export type Subscription = {
  expiresAt?: string; // Fecha de vencimiento (YYYY-MM-DD) o "evergreen"
  isActive: boolean;
};

export type CourseModule = {
  title: string;
  videoId: string;
};

export type PlatformType = "libros" | "audiolibros" | "resúmenes" | "educación" | "otros";

export type Resource = {
  id: string;
  title: string;
  author?: string;
  description?: string;
  type: ResourceType;
  category: string;
  status: Status;
  url?: string;
  tags?: string[];
  notes?: Note[];
  subscription?: Subscription;
  featured?: boolean;
  tema?: PodcastTema;
  affiliate?: boolean;
  modules?: CourseModule[];
  platformType?: PlatformType;
  coverUrl?: string;
};

export const categories: Category[] = [
  { id: "todos",             name: "Todos",              numeral: "∞",    color: "#B89455" },
  { id: "marketing",         name: "Marketing",          numeral: "I",    color: "#11503D" },
  { id: "ventas",            name: "Ventas",             numeral: "II",   color: "#166B4F" },
  { id: "negocios",          name: "Negocios",           numeral: "III",  color: "#11503D" },
  { id: "psicologia",        name: "Psicología",         numeral: "IV",   color: "#AB4A40" },
  { id: "espiritualidad",    name: "Espiritualidad",     numeral: "V",    color: "#1E8A66" },
  { id: "desarrollo-personal", name: "Desarrollo Personal", numeral: "VI", color: "#B89455" },
  { id: "finanzas",          name: "Finanzas",           numeral: "VII",  color: "#A6843F" },
  { id: "idiomas",           name: "Idiomas",            numeral: "VIII", color: "#897F66" },
];

export const statusLabels: Record<Status, string> = {
  "en-cola": "En cola",
  "leyendo": "En reproducción",
  "completado": "Completado",
};

export const statusColors: Record<Status, string> = {
  "en-cola":   "#B89455",   /* gold-500 — en espera       */
  "leyendo":   "#166B4F",   /* green-600 — en progreso    */
  "completado": "#5E5645",  /* bark-600 — finalizado      */
};

export const resourceTypeLabels: Record<ResourceType, string> = {
  "libro":      "Libro",
  "podcast":    "Podcast",
  "audiolibro": "Audiolibro",
  "documental": "Documental",
  "plataforma": "Plataforma",
  "youtube":    "YouTube",
  "curso":      "Curso",
};

export const podcastTemas: { id: PodcastTema; label: string; color: string }[] = [
  { id: "mentalidad",        label: "Mentalidad",        color: "#AB4A40" },
  { id: "dinero",            label: "Dinero",            color: "#A6843F" },
  { id: "negocios",          label: "Negocios",          color: "#11503D" },
  { id: "marketing",         label: "Marketing",         color: "#166B4F" },
  { id: "espiritualidad",    label: "Espiritualidad",    color: "#1E8A66" },
  { id: "desarrollo-personal", label: "Desarrollo Personal", color: "#5E5645" },
];

export const resources: Resource[] = [
  // ─── LIBROS ────────────────────────────────────────────────
  {
    id: "influencia",
    title: "Influencia",
    author: "Robert Cialdini",
    description: "Los principios psicológicos de la persuasión y cómo aplicarlos en ventas y marketing.",
    type: "libro",
    category: "ventas",
    status: "en-cola",
    tags: ["persuasión", "psicología", "ventas"],
  },
  {
    id: "fiesta-cocteles",
    title: "La fiesta de cócteles de dos horas",
    author: "Nico Gray",
    description: "Cómo construir relaciones valiosas y expandir tu red de contactos de forma auténtica.",
    type: "libro",
    category: "negocios",
    status: "en-cola",
    tags: ["networking", "relaciones", "social"],
  },
  {
    id: "disena-tu-vida",
    title: "Diseña tu vida",
    author: "Dave Evans y Bill Burnett",
    description: "Aplica el pensamiento de diseño para construir una vida significativa y satisfactoria.",
    type: "libro",
    category: "desarrollo-personal",
    status: "en-cola",
    tags: ["diseño", "propósito", "vida"],
  },
  {
    id: "montana-eres-tu",
    title: "La montaña eres tú",
    author: "Brianna Wiest",
    description: "Cómo superar el autosabotaje y transformar los obstáculos internos en fortaleza.",
    type: "libro",
    category: "psicologia",
    status: "en-cola",
    tags: ["autosabotaje", "crecimiento", "mentalidad"],
  },
  {
    id: "poder-conciencia",
    title: "El poder de la conciencia",
    author: "Neville Goddard",
    description: "Cómo usar la imaginación y la conciencia para manifestar la realidad deseada.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["manifestación", "conciencia", "ley de atracción"],
  },
  {
    id: "kybalion",
    title: "El Kybalion",
    author: "Tres Iniciados",
    description: "Los siete principios herméticos que gobiernan el universo y la mente humana.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["hermetismo", "filosofía", "principios"],
  },
  {
    id: "poder-mente-subconsciente",
    title: "El poder de tu mente subconsciente",
    author: "Joseph Murphy",
    description: "Técnicas para reprogramar el subconsciente y alcanzar el éxito y la prosperidad.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["subconsciente", "programación mental", "éxito"],
  },
  {
    id: "hombre-simbolos",
    title: "El hombre y sus símbolos",
    author: "Carl Jung",
    description: "Una exploración profunda del inconsciente y el lenguaje simbólico de los sueños.",
    type: "libro",
    category: "psicologia",
    status: "en-cola",
    tags: ["inconsciente", "sueños", "arquetipos"],
  },
  {
    id: "cabala-mistica",
    title: "La Cábala Mística",
    author: "Dion Fortune",
    description: "Estudio profundo del árbol de la vida y la tradición cabalística occidental.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["cábala", "misticismo", "árbol de la vida"],
  },
  {
    id: "corpus-hermeticum",
    title: "Corpus Hermeticum",
    author: "Hermes Trismegisto",
    description: "Textos fundacionales de la tradición hermética y la filosofía esotérica occidental.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["hermetismo", "filosofía antigua", "esotérico"],
  },
  {
    id: "fe-es-tu-fortuna",
    title: "Tu fe es tu fortuna",
    author: "Neville Goddard",
    description: "Cómo la fe y la imaginación son las fuerzas creadoras de nuestra realidad.",
    type: "libro",
    category: "espiritualidad",
    status: "en-cola",
    tags: ["fe", "manifestación", "imaginación"],
  },
  {
    id: "oversubscribed",
    title: "Oversubscribed",
    author: "Daniel Priestley",
    description: "Cómo construir un negocio tan demandado que los clientes hagan fila para comprarte.",
    type: "libro",
    category: "negocios",
    status: "en-cola",
    tags: ["demanda", "marketing", "posicionamiento"],
  },
  {
    id: "hiperdexconexion",
    title: "Hiperdexconexión",
    author: "Marta Romo",
    description: "Estrategias para conectar profundamente con tu audiencia en la era digital.",
    type: "libro",
    category: "marketing",
    status: "en-cola",
    tags: ["conexión", "audiencia", "digital"],
  },
  {
    id: "estrategia-conflicto",
    title: "La estrategia del conflicto",
    author: "Thomas Schelling",
    description: "Análisis estratégico de conflictos y negociaciones en economía y política.",
    type: "libro",
    category: "negocios",
    status: "en-cola",
    tags: ["estrategia", "conflicto", "negociación"],
  },
  {
    id: "generacion-dopamina",
    title: "Generación dopamina",
    author: "Anna Lembke",
    description: "Cómo el exceso de estimulación digital está afectando nuestra salud mental y bienestar.",
    type: "libro",
    category: "psicologia",
    status: "en-cola",
    tags: ["dopamina", "bienestar", "digital"],
  },
  {
    id: "12-reglas-vida",
    title: "12 Reglas para la vida",
    author: "Jordan Peterson",
    description: "Principios prácticos para vivir una vida significativa y responsable.",
    type: "libro",
    category: "desarrollo-personal",
    status: "en-cola",
    tags: ["responsabilidad", "significado", "vida"],
  },
  {
    id: "mindset",
    title: "Mindset",
    author: "Carol Dweck",
    description: "La mentalidad de crecimiento: cómo el pensamiento fijo limita y el flexible transforma.",
    type: "libro",
    category: "desarrollo-personal",
    status: "en-cola",
    tags: ["mentalidad", "crecimiento", "aprendizaje"],
  },
  {
    id: "quien-no-como",
    title: "Quién no como",
    author: "Dan Sullivan",
    description: "Cómo identificar y eliminar las personas que sabotean tu éxito y crecimiento.",
    type: "libro",
    category: "desarrollo-personal",
    status: "en-cola",
    tags: ["relaciones", "éxito", "límites"],
  },
  {
    id: "puedes-negociar-cualquier-cosa",
    title: "Puedes negociar cualquier cosa",
    author: "Herb Cohen",
    description: "Técnicas prácticas y probadas para negociar efectivamente en cualquier situación.",
    type: "libro",
    category: "ventas",
    status: "en-cola",
    tags: ["negociación", "ventas", "comunicación"],
  },
  {
    id: "10-es-mas-facil-que-2",
    title: "10. Es más fácil que 2",
    author: "Dan Sullivan",
    description: "Por qué es más fácil lograr objetivos 10 veces mayores que objetivos apenas mejores.",
    type: "libro",
    category: "negocios",
    status: "en-cola",
    tags: ["objetivos", "crecimiento", "mentalidad"],
  },
  // ─── LIBROS FAVORITOS RECOMENDADOS ──────────────────────────
  {
    id: "secretos-mente-millonaria",
    title: "Los secretos de una mente millonaria",
    author: "T. Harv Eker",
    description: "Los patrones de pensamiento que separan a los ricos de los pobres. Cómo reprogramar tu mentalidad financiera.",
    type: "libro",
    category: "finanzas",
    status: "completado",
    tags: ["mentalidad", "riqueza", "finanzas personales", "hábitos"],
    featured: true,
  },
  {
    id: "problema-dinero-eres-tu",
    title: "El problema no es el dinero, eres tú",
    author: "Jen Sincero",
    description: "Identifica y supera los bloqueos mentales que te impiden generar y mantener riqueza.",
    type: "libro",
    category: "finanzas",
    status: "completado",
    tags: ["mentalidad", "dinero", "transformación", "abundancia"],
    featured: true,
  },
  {
    id: "piense-hagase-rico",
    title: "Piense y hágase Rico",
    author: "Napoleon Hill",
    description: "Clásico sobre cómo el pensamiento crea realidad. Principios fundamentales para generar riqueza y éxito.",
    type: "libro",
    category: "finanzas",
    status: "completado",
    tags: ["clásico", "éxito", "riqueza", "principios"],
    featured: true,
  },
  {
    id: "aprendiendo-mejores",
    title: "Aprendiendo de los mejores",
    author: "Varios autores",
    description: "Lecciones y estrategias de emprendedores y empresarios exitosos de América Latina.",
    type: "libro",
    category: "negocios",
    status: "completado",
    tags: ["emprendimiento", "mentalidad", "estrategia", "éxito"],
    featured: true,
  },
  {
    id: "zonas-erroneas",
    title: "Zonas Erroneas",
    author: "Wayne Dyer",
    description: "Cómo identificar y eliminar patrones de pensamiento autolimitantes que obstaculizan tu felicidad.",
    type: "libro",
    category: "psicologia",
    status: "completado",
    tags: ["psicología", "autosabotaje", "libertad", "consciencia"],
    featured: true,
  },
  {
    id: "juego-vida-como-jugarlo",
    title: "El Juego de la vida y cómo jugarlo",
    author: "Florence Scovel Shinn",
    description: "Revelaciones sobre las leyes espirituales del universo y cómo atraer lo que deseas.",
    type: "libro",
    category: "espiritualidad",
    status: "completado",
    tags: ["manifestación", "leyes universales", "abundancia", "espíritu"],
    featured: true,
  },
  {
    id: "21-creencias-amargan-vida",
    title: "21 creencias que te amargan la vida",
    author: "Varios autores",
    description: "Identifica las creencias limitantes que te mantienen estancado y aprende a transformarlas.",
    type: "libro",
    category: "psicologia",
    status: "completado",
    tags: ["creencias", "transformación", "mentalidad", "crecimiento"],
    featured: true,
  },
  {
    id: "placebo-eres-tu",
    title: "El placebo eres tú",
    author: "Joe Dispenza",
    description: "Cómo el poder de la mente puede transformar tu realidad física y emocional.",
    type: "libro",
    category: "espiritualidad",
    status: "completado",
    tags: ["mente", "transformación", "consciente", "realidad"],
    featured: true,
  },
  // ─── YOUTUBE ────────────────────────────────────────────────
  {
    id: "yt-diary-ceo",
    title: "The Diary of a CEO",
    description: "Steven Bartlett comparte historias de emprendimiento, negocios y mentalidad de éxito con invitados de alto nivel.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@TheDiaryOfACEO",
    tags: ["negocios", "emprendimiento", "mentalidad"],
  },
  {
    id: "yt-lewis-howes",
    title: "Lewis Howes Español",
    description: "Contenido de Lewis Howes sobre éxito, relaciones, negocios y desarrollo personal en español.",
    type: "youtube",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.youtube.com/@LewisHowesEspañol",
    tags: ["éxito", "relaciones", "desarrollo personal"],
  },
  {
    id: "yt-dan-martell",
    title: "Dan Martell",
    description: "Estrategias de crecimiento, escalamiento de negocios y productividad para emprendedores.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@danmartell",
    tags: ["crecimiento", "negocios", "productividad"],
  },
  {
    id: "yt-grant-cardone",
    title: "Grant Cardone",
    description: "Técnicas de ventas, negocios y mentalidad de abundancia para alcanzar el éxito.",
    type: "youtube",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/@GrantCardone",
    tags: ["ventas", "negocios", "mentalidad"],
  },
  {
    id: "yt-kale-anders",
    title: "Kale Anders",
    description: "Marketing digital, negocios online y estrategias de crecimiento para emprendedores.",
    type: "youtube",
    category: "marketing",
    status: "en-cola",
    url: "https://www.youtube.com/@KaleAnders",
    tags: ["marketing", "negocios digitales", "crecimiento"],
  },
  {
    id: "yt-alex-hormozi",
    title: "Alex Hormozi",
    description: "Adquisición de empresas, ventas de alto nivel y escalamiento de negocios rentables.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@AlexHormozi",
    tags: ["negocios", "ventas", "escalamiento"],
  },
  {
    id: "yt-daniel-chapan",
    title: "Daniel Chapan",
    description: "Contenido sobre psicología, desarrollo personal, mentalidad y transformación de vida.",
    type: "youtube",
    category: "psicologia",
    status: "en-cola",
    url: "https://www.youtube.com/@DanielChapan",
    tags: ["psicología", "mentalidad", "transformación"],
  },
  {
    id: "yt-simon-squibb",
    title: "Simon Squibb",
    description: "Estrategias de negocios, emprendimiento y mentalidad empresarial para crecer exponencialmente.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@SimonSquibb",
    tags: ["negocios", "emprendimiento", "estrategia"],
  },
  {
    id: "yt-sadhguru-espanol",
    title: "Sadhguru Español",
    description: "Enseñanzas sobre espiritualidad, meditación, consciencia y transformación personal.",
    type: "youtube",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://www.youtube.com/@SadhguruEspañol",
    tags: ["espiritualidad", "meditación", "consciencia"],
  },
  {
    id: "yt-manuel-trejove",
    title: "Manuel Trejove",
    description: "Contenido sobre marketing, negocios digitales y estrategias de crecimiento online.",
    type: "youtube",
    category: "marketing",
    status: "en-cola",
    url: "https://www.youtube.com/@manueltrejove",
    tags: ["marketing", "negocios digitales", "estrategia"],
  },
  {
    id: "yt-tony-robbins",
    title: "Tony Robbins Live",
    description: "Seminarios y contenido de Tony Robbins sobre éxito, finanzas y transformación personal.",
    type: "youtube",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.youtube.com/@TonyRobbinsLive",
    tags: ["éxito", "finanzas", "transformación"],
  },
  {
    id: "yt-borja-vilaseca",
    title: "Borja Vilaseca",
    description: "Reflexiones sobre filosofía, desarrollo personal y transformación de consciencia.",
    type: "youtube",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://www.youtube.com/@borjavilaseca",
    tags: ["filosofía", "consciencia", "transformación"],
  },
  {
    id: "yt-financial-mentors",
    title: "Financial Mentors TV Español",
    description: "Educación financiera, inversión y estrategias para construir riqueza.",
    type: "youtube",
    category: "finanzas",
    status: "en-cola",
    url: "https://www.youtube.com/c/FinancialMentorsTVEspañol",
    tags: ["finanzas", "inversión", "riqueza"],
  },
  {
    id: "yt-shark-tank-latam",
    title: "Shark Tank Latam",
    description: "Pitch de emprendedores y análisis de negocios con inversionistas destacados.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@SharkTankLatam",
    tags: ["negocios", "emprendimiento", "inversión"],
  },
  {
    id: "yt-tengo-un-plan",
    title: "Tengo un Plan Podcast",
    description: "Podcast sobre emprendimiento, negocios y mentalidad de éxito.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@tengounplanpodcast",
    tags: ["emprendimiento", "negocios", "podcast"],
  },
  {
    id: "yt-dieck-docks",
    title: "DieckDocks",
    description: "Canal de YouTube con contenido sobre negocios, emprendimiento y estrategias de crecimiento.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@DieckDocks",
    tags: ["negocios", "emprendimiento", "estrategia"],
  },
  {
    id: "yt-evan-en-espanol",
    title: "Evan en Español",
    description: "Canal en español con contenido de mentalidad, éxito y desarrollo personal, destacando ideas de pensadores como Jordan Peterson.",
    type: "youtube",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.youtube.com/@EvanenEspanol",
    tags: ["mentalidad", "éxito", "desarrollo personal", "filosofía"],
  },
  {
    id: "yt-greatness-clips-espanol",
    title: "Greatness Clips - Español",
    description: "Clips en español de entrevistas con figuras de alto nivel como Grant Cardone, Lewis Howes y otros referentes del éxito y los negocios.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@GreatnessClipsEspanol",
    tags: ["negocios", "éxito", "entrevistas", "millonarios"],
  },
  {
    id: "yt-libros-para-emprendedores",
    title: "Libros para Emprendedores",
    description: "Luis Ramos presenta resúmenes de los mejores libros de negocios, emprendimiento y desarrollo personal para empresarios en crecimiento.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@LibrosParaEmprendedores",
    tags: ["libros", "emprendimiento", "resúmenes", "negocios"],
  },
  {
    id: "yt-mark-tilbury",
    title: "Mark Tilbury",
    description: "Educación financiera, inversión y estrategias para construir riqueza y libertad financiera.",
    type: "youtube",
    category: "finanzas",
    status: "en-cola",
    url: "https://www.youtube.com/@marktilbury",
    tags: ["finanzas", "inversión", "riqueza"],
  },
  {
    id: "yt-history-latinoamerica",
    title: "History Latinoamérica",
    description: "Canal oficial de History Channel en Latinoamérica. Documentales, series y programas sobre historia, misterios, ciencia, tecnología y fenómenos inexplicables.",
    type: "youtube",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://www.youtube.com/@HistoryLatinoamerica",
    tags: ["documental", "historia", "misterio", "History Channel"],
  },
  {
    id: "yt-liderazgo-poderoso",
    title: "LIDERAZGO PODEROSO",
    description: "Seminarios y conferencias de grandes referentes del liderazgo, ventas y negocios: Harvey Mackay, Lisa Ford y otros expertos de talla mundial en español.",
    type: "youtube",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/@liderazgopoderosooficial",
    tags: ["liderazgo", "ventas", "negocios", "conferencias"],
  },
  // ─── PLATAFORMAS ────────────────────────────────────────────
  {
    id: "plat-mindvalley",
    title: "Mindvalley",
    description: "Plataforma de aprendizaje con cursos de desarrollo personal, meditación, y transformación de vida.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://home.mindvalley.com/today",
    tags: ["desarrollo personal", "cursos", "meditación"],
    affiliate: true,
    subscription: {
      expiresAt: "2028-11-18",
      isActive: true,
    },
  },
  {
    id: "plat-masterclass",
    title: "MasterClass",
    description: "Plataforma de cursos en línea con clases de maestros reconocidos en diversos campos.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.masterclass.com/homepage",
    tags: ["cursos", "maestros", "aprendizaje"],
    affiliate: true,
    subscription: {
      expiresAt: "2026-08-17",
      isActive: true,
    },
  },
  {
    id: "plat-weplash",
    title: "WePlay Academy",
    description: "Academia de aprendizaje con cursos especializados en creatividad y desarrollo profesional.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://academia.weplash.com/feed",
    tags: ["academia", "creatividad", "profesional"],
    affiliate: true,
    subscription: {
      expiresAt: "2026-06-30",
      isActive: true,
    },
  },
  {
    id: "plat-marisa-peer",
    title: "Marisa Peer - Reshape Your Future",
    description: "Programas de hipnosis y transformación personal con Marisa Peer para cambiar creencias limitantes.",
    type: "plataforma",
    category: "psicologia",
    status: "en-cola",
    url: "https://marisapeer.mykajabi.com/products/reshape-your-future-with-hypnosis/categories/2156439401/posts/2182477995",
    tags: ["hipnosis", "transformación", "creencias"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-mastermind",
    title: "Official Mastermind",
    description: "Comunidad y plataforma de mastermind para emprendedores y líderes en crecimiento.",
    type: "plataforma",
    category: "negocios",
    status: "en-cola",
    url: "https://official.mastermind.com/c/start-here",
    tags: ["mastermind", "emprendimiento", "comunidad"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  // ─── PLATAFORMAS DE LIBROS Y AUDIOLIBROS ────────────────────
  {
    id: "plat-audible",
    title: "Audible",
    description: "Plataforma de audiolibros de Amazon con millones de títulos narrados profesionalmente. Acceso a libros de desarrollo personal, negocios, ficción, historia y más.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.audible.com/",
    tags: ["audiolibros", "narración profesional", "acceso ilimitado", "aprendizaje"],
    featured: true,
    platformType: "audiolibros",
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-storytell",
    title: "Storytell",
    description: "Plataforma latinoamericana de audiolibros con títulos en español. Enfocada en desarrollo personal, ficción, historia y educación.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.storytellatl.com/",
    tags: ["audiolibros", "español", "desarrollo personal", "comunidad"],
    featured: true,
    platformType: "audiolibros",
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-wiser",
    title: "Wiser - Resúmenes de Libros",
    description: "Plataforma de resúmenes de libros de no-ficción. Aprende los conceptos clave de los mejores libros de desarrollo personal, negocios y más en 15 minutos.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://wiser.com/",
    tags: ["resúmenes", "libros", "conceptos clave", "aprendizaje rápido"],
    featured: true,
    platformType: "resúmenes",
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-scribd",
    title: "Scribd",
    description: "Biblioteca digital con millones de libros, audiolibros, revistas y documentos. Acceso ilimitado a contenido educativo y de entretenimiento.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.scribd.com/",
    tags: ["libros", "audiolibros", "revistas", "documentos", "acceso ilimitado"],
    featured: true,
    platformType: "libros",
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-everand",
    title: "Everand",
    description: "Plataforma de lectura digital con ebooks, audiolibros y documentos. Acceso a miles de títulos de no-ficción, desarrollo personal y más.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://www.everand.com/",
    tags: ["ebooks", "audiolibros", "lectura digital", "no-ficción"],
    featured: true,
    platformType: "libros",
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  // ─── CURSOS EDUARDO ROSSER — MAGISTRAL ──────────────────────
  {
    id: "curso-rosser-persuasion",
    title: "Persuasión — Curso Completo",
    author: "Eduardo Rosser · MAGISTRAL",
    description: "Curso completo de persuasión aplicada a ventas y comunicación. 27 módulos que cubren desde los fundamentos psicológicos hasta técnicas avanzadas de influencia, manejo de objeciones y argumentación.",
    type: "curso",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/watch?v=NIGdVgViLjY&list=PLLGVeFOeEGJbgClqioujsrbQD6I83246-",
    tags: ["persuasión", "ventas", "comunicación", "influencia", "Eduardo Rosser"],
    featured: true,
    modules: [
      { title: "Introducción", videoId: "NIGdVgViLjY" },
      { title: "¿Me vigilas las cosas?", videoId: "pZZgTKdweDc" },
      { title: "Algo diferente", videoId: "5NV0p8RUySw" },
      { title: "Mamá, gracias por los pañales", videoId: "h8h6z7MkQBY" },
      { title: "¿Puedo ayudarle en algo?", videoId: "z-HNovrq9HU" },
      { title: "Consigue un aumento de sueldo", videoId: "WaYIO0Y_1rI" },
      { title: "Tal vez seas idiota y no lo sabes", videoId: "SSc_ddVxzq8" },
      { title: "¿Una cuestión de estilo?", videoId: "yIBIz3sVkIE" },
      { title: "Frenos y aceleradores", videoId: "sypCNTn0v6w" },
      { title: "El enemigo público número 1", videoId: "dUHiuEt2SYo" },
      { title: "Los listos molestan", videoId: "BdwnbqkTMWE" },
      { title: "Razones y emociones", videoId: "4gxNAgr6aUg" },
      { title: "Enseñar la cocina", videoId: "0waSvfmuSyo" },
      { title: "Los colchones de Yecla", videoId: "GaoLifMT08I" },
      { title: "Anda... ¡ayúdale un poco!", videoId: "InrkpaNhros" },
      { title: "Tú no existes", videoId: "jVjmP9hRPCw" },
      { title: "La muñeca meona", videoId: "xNhiQng3kZU" },
      { title: "Salvar la cara", videoId: "33PUE8_q_TA" },
      { title: "Glory hole", videoId: "tGYwIjJaDqM" },
      { title: "Siempre el dichoso precio", videoId: "G2BT7W5ywiI" },
      { title: "Buscando el \"no\"", videoId: "4Fv-nN7VhdI" },
      { title: "Promesas del este", videoId: "jfn1isGAtjQ" },
      { title: "Lo que más le impacta al cerebro", videoId: "bA9i1iqrFZk" },
      { title: "La argumentación australiana", videoId: "vQ69OBiTEkI" },
      { title: "Déjate de cuentos", videoId: "e8TW2lzEIRo" },
      { title: "La ley seca", videoId: "_LCabZGml9E" },
      { title: "Síntesis final", videoId: "mIM4gU_Ty-0" },
    ],
  },
  {
    id: "curso-rosser-storytelling",
    title: "Storytelling de Ventas — Curso Completo",
    author: "Eduardo Rosser · MAGISTRAL",
    description: "Domina el arte de contar historias que venden. 39 módulos sobre narrativa comercial: cómo construir relatos pegadizos, generar credibilidad, conectar emocionalmente y guiar al cliente hacia la decisión.",
    type: "curso",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/watch?v=uDsZdkJyiHA&list=PLLGVeFOeEGJYyJ-54AgwWZeYLtoB8rZ7q",
    tags: ["storytelling", "ventas", "narrativa", "comunicación", "Eduardo Rosser"],
    featured: true,
    modules: [
      { title: "Introducción", videoId: "uDsZdkJyiHA" },
      { title: "Relatos pegadizos que venden", videoId: "cNCRPsHvQ7k" },
      { title: "La economía de la atención", videoId: "8xX2NlFZR7U" },
      { title: "Ventajas del relato y un GPS", videoId: "6KPeEa2eQ-w" },
      { title: "Cómo hacerlo recordable", videoId: "U_7kA0jD9Xk" },
      { title: "Cómo hacerlo lúdico", videoId: "WgdrXktyYuA" },
      { title: "Cómo hacerlo no invasivo", videoId: "fxtb4Lpf5Xo" },
      { title: "Pensamos en historias", videoId: "YFQsjgDnIHM" },
      { title: "Claridad y atención", videoId: "XVLdW6eaQyc" },
      { title: "Demostración", videoId: "EKn-5yr-eDk" },
      { title: "Cercanía", videoId: "c3DE0K6-UTs" },
      { title: "Comprensión", videoId: "CXXQd_ex7Ws" },
      { title: "Credibilidad", videoId: "P4vd0FR0w3E" },
      { title: "Misticismo", videoId: "T5GzfhqijsQ" },
      { title: "Personalización", videoId: "nLKj_kYP3eQ" },
      { title: "Interactividad", videoId: "F0GFfUgGR1w" },
      { title: "Primer ingrediente: conflicto", videoId: "9aEtH2JNvWM" },
      { title: "Detalles", videoId: "ZaPe6OnW5Vg" },
      { title: "Repeticiones", videoId: "4oxB6z_3hdQ" },
      { title: "Contraste", videoId: "3aEeNdgEVQk" },
      { title: "Estructura", videoId: "Yek1TvdKwtQ" },
      { title: "Introducción, nudo y desenlace", videoId: "2AZz0MXB6UU" },
      { title: "Historias más o menos reales", videoId: "ZtaXQqzMwRw" },
      { title: "Problema, consecuencias y soluciones", videoId: "RZwBv3SWnEc" },
      { title: "Target", videoId: "sok2FywfWm4" },
      { title: "Autoría", videoId: "t8l9QmqfDLI" },
      { title: "¿Mentiras?", videoId: "y5HfNIKon2I" },
      { title: "Comprimir", videoId: "RK8QTKJFQ3k" },
      { title: "Improvisación", videoId: "K4JF_3Hwhw8" },
      { title: "Inventario comercial de relatos", videoId: "nUABqPT8ziI" },
      { title: "Buscar más info", videoId: "TTB-h5-rrmk" },
      { title: "Tres es multitud", videoId: "gIgSH-lvkgU" },
      { title: "Hábitos y acomodo", videoId: "w_u-pW5Fk0I" },
      { title: "Enseñar a pensar", videoId: "HTPUCM15ATQ" },
      { title: "Puntos de vista", videoId: "JOC_ATBs4tY" },
      { title: "Reciclaje", videoId: "dcPPgWikKDg" },
      { title: "Prejuicios", videoId: "WHj5N6EnDD0" },
      { title: "Problema / oportunidad", videoId: "A7lKXGvKivw" },
      { title: "Síntesis final", videoId: "5TJq3STNkyI" },
    ],
  },
  {
    id: "curso-rosser-vender-sin-bajar-precios",
    title: "Vender Sin Bajarte los Pantalones — Curso Completo",
    author: "Eduardo Rosser · MAGISTRAL",
    description: "27 módulos para vender sin entrar en guerra de precios. Aprende a defender tu valor, identificar al comprador de precio falso, construir propuestas de valor sólidas y negociar desde una posición de fuerza.",
    type: "curso",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/watch?v=p3NBDZJGJfE&list=PLLGVeFOeEGJbkIVA6ns5aaURp-e-6rkwh",
    tags: ["precios", "ventas", "valor", "negociación", "Eduardo Rosser"],
    featured: true,
    modules: [
      { title: "Introducción", videoId: "p3NBDZJGJfE" },
      { title: "El camino fácil pero incorrecto", videoId: "h9KyK3hGPKo" },
      { title: "No hay vida en la guerra de precios", videoId: "q4-b1f1X9is" },
      { title: "Obsesión dual", videoId: "WvFTtuTP53E" },
      { title: "¿Solo precio? Tú y yo sobramos", videoId: "awFgFDeRF1k" },
      { title: "Estoy contento con mi proveedor", videoId: "pBhJDYa0TpE" },
      { title: "La trampa de la rentabilidad", videoId: "LsBfaSOp97k" },
      { title: "La peor pesadilla de un vendedor", videoId: "1cuQh9VUCjI" },
      { title: "Fijando el precio correcto", videoId: "xZvruGh-t6A" },
      { title: "Coste y valor: un equilibrio necesario", videoId: "yfWbhe8ZYz0" },
      { title: "¿No querrás ser un pagafantas?", videoId: "89ZKQMBNxqs" },
      { title: "4 tipos de clientes... teóricos", videoId: "iQial5eALnE" },
      { title: "Precio y valor: las pescadillas muerden", videoId: "2kKyTKv8vpc" },
      { title: "Vendemos lo mismo: propuesta de valor", videoId: "wfYxqe40Uco" },
      { title: "Descubrir al falso comprador de precio", videoId: "mdnNLCDq1ds" },
      { title: "Precio y algo más", videoId: "8BADimRRfYA" },
      { title: "Antes de la batalla, un aperitivo", videoId: "FLYc1raOL3Y" },
      { title: "Siete caminos llegan a Roma", videoId: "TiUsYThiRSU" },
      { title: "Opción 1: \"Sí... bajada de pantalones\"", videoId: "uJbKubSR_V8" },
      { title: "Opción 2: \"Es lo que hay\"", videoId: "SKwypF4Otmc" },
      { title: "Opción 3: \"No, el más clásico y quemado\"", videoId: "M1UvtctPumo" },
      { title: "Opción 4: \"No: lo barato sale caro\"", videoId: "od1Wc73IODg" },
      { title: "Intro a los 3 enfoques \"cool\"", videoId: "g29NKsRoGJI" },
      { title: "Opción 5: \"Sí, cuidando margen\" — Parte 1", videoId: "2tdc7WwYpZY" },
      { title: "Opción 5: \"Sí, cuidando margen\" — Parte 2", videoId: "oDzPb4dZsmY" },
      { title: "No, sin megas", videoId: "NP-i60bjF3Y" },
      { title: "Síntesis final", videoId: "5zPsjpFzi7Q" },
    ],
  },
  {
    id: "curso-rosser-negociacion-dificil",
    title: "Negociación con Clientes y Proveedores Difíciles — Curso Completo",
    author: "Eduardo Rosser · MAGISTRAL",
    description: "27 módulos de negociación avanzada. Técnicas para gestionar clientes y proveedores exigentes: variables ocultas, escucha selectiva, el método del NO, preguntas pronóstico y cómo salir de negociaciones estancadas.",
    type: "curso",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/watch?v=pNoO95h2pZ8&list=PLLGVeFOeEGJaqpd0j0rzw8CVId1vSNfhk",
    tags: ["negociación", "clientes", "proveedores", "técnicas", "Eduardo Rosser"],
    featured: true,
    modules: [
      { title: "Lo que muchos creen que es negociar", videoId: "pNoO95h2pZ8" },
      { title: "Esto no lo tengo tan claro", videoId: "9X1vPi-O3AI" },
      { title: "Un comienzo a ciegas", videoId: "j3tAcYNI7HE" },
      { title: "Un comienzo a ciegas (solución)", videoId: "w6XougfZ5T8" },
      { title: "Vender y comprar con/sin negociación", videoId: "yDa3HfhnGtM" },
      { title: "Los Beatles, negociación TOP", videoId: "blt70QKSfBM" },
      { title: "Cada cliente NO es un mundo", videoId: "9QLmj7tiQAU" },
      { title: "Las variables ocultas", videoId: "z2B2cpwQDNg" },
      { title: "No necesidad: apuestas perdedoras", videoId: "ohAZyi5Q3k8" },
      { title: "Casemiro y el lado oculto", videoId: "2-y6yj9wKV8" },
      { title: "El negociador \"experto ignorante\"", videoId: "jO5Jq-aI4oU" },
      { title: "No OK: ¿quién debe estar cómodo?", videoId: "v6UhQDTV5fc" },
      { title: "¿Muestro mis cartas... o no las muestro?", videoId: "YNW0I32RzPs" },
      { title: "Antes de la negociación — Parte 1", videoId: "5lYX_TNKd_8" },
      { title: "Antes de la negociación — Parte 2", videoId: "Uoaaq23ohhg" },
      { title: "Antes de la negociación — Parte 3", videoId: "JNZhSGP7JjY" },
      { title: "No dar soluciones (pregunta pronóstico)", videoId: "4UazpF_FiB0" },
      { title: "No a la primera (cómo repreguntar)", videoId: "Selg4Vi3mZc" },
      { title: "No escuchar todo (escucha selectiva)", videoId: "1erW-jTi6z8" },
      { title: "No interpretar (Iceberg + Quid pro quo)", videoId: "B4OTo40MnPU" },
      { title: "La repetición genera familiaridad", videoId: "9S3mxPzeMso" },
      { title: "El método del NO", videoId: "q3pwTV4pH28" },
      { title: "Invitar al NO", videoId: "IGr1Ecg1YT8" },
      { title: "Recibir el NO", videoId: "2HKnjCkTIlo" },
      { title: "Decir NO", videoId: "OFr5pgCYeb4" },
      { title: "Negociación estancada", videoId: "3afhXj8slw0" },
      { title: "Conclusión de la falla", videoId: "RC17-3eX63I" },
    ],
  },
  // ─── PODCASTS (Videos sueltos) ────────────────────────────────
  {
    id: "podcast-7-things-avoid-rich",
    title: "7 Cosas que Debes Evitar si Quieres Ser Rico",
    description: "Mark Tilbury comparte 7 cosas que debes evitar si quieres ser rico. Estrategias clave para la riqueza.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/KMbFjoHUYbA",
    tags: ["riqueza", "finanzas", "estrategia"],
    tema: "dinero",
  },
  {
    id: "podcast-wish-knew-business",
    title: "Lo Que Desearía Haber Sabido Antes de Empezar un Negocio",
    description: "Lecciones clave de Mark Tilbury sobre qué desearía haber sabido antes de empezar un negocio.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/A54VFBYfF9U",
    tags: ["emprendimiento", "negocios", "lecciones"],
    tema: "negocios",
  },
  {
    id: "podcast-started-scratch",
    title: "Si Empezara de Cero Nuevamente, Haría Esto",
    description: "Mark Tilbury revela qué haría diferente si empezara de cero en su camino hacia la riqueza.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/6IiEoSHw9gY",
    tags: ["finanzas", "estrategia", "experiencia"],
    tema: "dinero",
  },
  {
    id: "podcast-7-signs-millionaire",
    title: "7 Señales de que Serás Millonario Pronto",
    description: "Mark Tilbury identifica 7 señales que indican que te convertirás en millonario pronto.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/JqJ2l4frTrU",
    tags: ["riqueza", "millonario", "señales"],
    tema: "dinero",
  },
  {
    id: "podcast-print-on-demand",
    title: "La Única Guía de Print On Demand que Necesitas en 2026 (Con IA)",
    description: "Guía completa de print on demand con AI para principiantes. Cómo generar ingresos pasivos.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/9tKeNT-k4kk",
    tags: ["negocios", "AI", "ingresos pasivos"],
    tema: "negocios",
  },
  {
    id: "podcast-paycheck-routine",
    title: "Haz Esto Cada Vez que Recibas tu Salario (Rutina 2026)",
    description: "Rutina de Mark Tilbury para gestionar tu salario y construir riqueza consistentemente.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/sPm9pynCS0k",
    tags: ["finanzas", "presupuesto", "hábitos"],
    tema: "dinero",
  },
  {
    id: "podcast-10k-month-route",
    title: "La Ruta Más Inteligente para Ganar $10,000/Mes en 2026",
    description: "La ruta más inteligente para generar $10,000 mensuales según Mark Tilbury.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/mwYsapR6cYk",
    tags: ["ingresos", "negocios", "estrategia"],
    tema: "negocios",
  },
  {
    id: "podcast-smartest-financial-freedom",
    title: "El Camino Más Inteligente Hacia la Libertad Financiera en 2026",
    description: "Camino más inteligente hacia la libertad financiera con estrategias probadas.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/C_UeYBBogPA",
    tags: ["libertad financiera", "estrategia", "finanzas"],
    tema: "dinero",
  },
  {
    id: "podcast-ai-dropshipping",
    title: "Probé Dropshipping con IA Durante una Semana (Resultados Reales)",
    description: "Experimento de Mark Tilbury con dropshipping potenciado por AI. Resultados reales.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/rhuYy9LP72M",
    tags: ["dropshipping", "AI", "ecommerce"],
    tema: "negocios",
  },
  {
    id: "podcast-10k-student",
    title: "Haz Esto para Ganar $10,000 Como Estudiante",
    description: "Guía práctica para estudiantes que quieren ganar $10,000 rápidamente.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/BvDAUqLQ-uc",
    tags: ["estudiantes", "ingresos", "negocios"],
    tema: "negocios",
  },
  {
    id: "podcast-24-hours-richest-entrepreneur",
    title: "Pasé 24 Horas con el Empresario de YouTube Más Rico",
    description: "Experiencia de 24 horas con un empresario exitoso de YouTube. Lecciones y insights valiosos.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/cLdMjVvP7kE",
    tags: ["emprendimiento", "YouTube", "éxito"],
    tema: "negocios",
  },
  {
    id: "podcast-money-making-expert-priestley",
    title: "El Experto en Ganar Dinero: La Fórmula Exacta para Convertir $100 en $100k por Mes",
    description: "Daniel Priestley revela la fórmula exacta para convertir $100 en $100,000 mensuales. Estrategias de emprendimiento probadas.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/u0o3IlsEQbI",
    tags: ["emprendimiento", "dinero", "estrategia"],
    tema: "negocios",
  },
  {
    id: "podcast-seminario-fenix-brian-tracy",
    title: "Seminario Fénix Brian Tracy Completo en Español",
    description: "Seminario completo de Brian Tracy sobre psicología del éxito, mentalidad y logro de objetivos. Destacado.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/zUxj7J8HttM",
    tags: ["éxito", "mentalidad", "seminario"],
    featured: true,
    tema: "mentalidad",
  },
  {
    id: "podcast-oz-pearlman-mentalist",
    title: "Oz Pearlman (Mentalista): Este Pequeño Error Hace que la Gente No te Acepte",
    description: "El mentalista Oz Pearlman revela cómo leer a las personas, construir confianza y ganar atención. Destacado.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/4qfxHfBJ3Mw",
    tags: ["psicología", "lenguaje corporal", "mentalismo"],
    featured: true,
    tema: "mentalidad",
  },
  {
    id: "podcast-tony-robbins-ai-future",
    title: "Tony Robbins: Nadie Está Listo para lo que Viene (La Verdad sobre la IA)",
    description: "Tony Robbins advierte sobre el futuro de la IA y su impacto psicológico. Reflexiones sobre el cambio y la adaptación.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/I_w81rptxkc",
    tags: ["IA", "futuro", "mentalidad"],
    tema: "mentalidad",
  },
  {
    id: "podcast-alex-hormozi-millionaires",
    title: "El Hombre que Crea Millonarios: Convierte $0 en $10k con Esta Fórmula Paso a Paso",
    description: "Alex Hormozi comparte la fórmula exacta para convertir $0 en $10,000 mensuales. Estrategias de negocios probadas. Destacado.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/Kl-I7sUcAOY",
    tags: ["emprendimiento", "dinero", "negocios"],
    featured: true,
    tema: "negocios",
  },
  {
    id: "podcast-vanessa-van-edwards-body-language",
    title: "Experta en Lenguaje Corporal: Deja de Usar Esto, Hace que la Gente No te Acepte",
    description: "Vanessa Van Edwards, experta en lenguaje corporal, revela los secretos para ser más carismático y conectar con otros.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/VHUrdELKjDw",
    tags: ["lenguaje corporal", "carisma", "comunicación"],
    tema: "mentalidad",
  },
  {
    id: "plat-executive-business",
    title: "Executive Business Experience - Vanguardia Summit",
    description: "Programa de negocios ejecutivos y experiencia en cumbre de vanguardia empresarial.",
    type: "plataforma",
    category: "negocios",
    status: "en-cola",
    url: "https://executive-business-experience.mykajabi.com/library",
    tags: ["negocios", "ejecutivos", "cumbre"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-coco-marca-personal",
    title: "Programa COCO y Marca Personal",
    description: "Programa completo para construir tu marca personal y presencia online.",
    type: "plataforma",
    category: "marketing",
    status: "en-cola",
    url: "https://jump.vilmanunez.com/library",
    tags: ["marca personal", "marketing", "presencia online"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-rpm-method",
    title: "Método RPM - Tony Robbins",
    description: "Método RPM (Resultados, Propósito, Motivación) de Tony Robbins para lograr objetivos.",
    type: "plataforma",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://tonyrobbinsrpm.com/client/index.php",
    tags: ["RPM", "objetivos", "motivación"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-raio-program",
    title: "Programa RAIO - Kale Anders",
    description: "Programa RAIO en inglés de Kale Anders para crecimiento empresarial acelerado.",
    type: "plataforma",
    category: "idiomas",
    status: "en-cola",
    url: "https://kaleanders.clickfunnels.com/members/sign_in",
    tags: ["RAIO", "crecimiento", "inglés"],
    affiliate: true,
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "plat-ai-creator-course",
    title: "AI Creator Course - Edición de Video",
    description: "Curso de creación de contenido con IA enfocado en edición de video profesional.",
    type: "plataforma",
    category: "marketing",
    status: "en-cola",
    url: "https://www.contentcreator.com/ai-creator-course",
    tags: ["IA", "video", "edición", "contenido"],
    subscription: {
      expiresAt: "evergreen",
      isActive: true,
    },
  },
  {
    id: "podcast-chris-koerner-passive-income",
    title: "Experto en Ingresos Pasivos: Cómo Ganar $10k Mensuales en 90 Días",
    description: "Chris Koerner, el Rey de los Side Hustles, revela cómo construyó 80+ negocios desde cero y convirtió sus emprendimientos laterales en millones. Destacado.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/4QLWlcneJig",
    tags: ["ingresos pasivos", "emprendimiento", "side hustles", "negocios"],
    featured: true,
    tema: "negocios",
  },
  {
    id: "podcast-ryan-holiday-discipline",
    title: "The Discipline Expert: 2,000 Years Of Research PROVES Successful People Do One Thing!",
    author: "Ryan Holiday",
    description: "Análisis de disciplina y hábitos de personas exitosas basado en investigación histórica. Ryan Holiday revela el factor clave que caracteriza el éxito.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/PafvhTSC4yE",
    tags: ["disciplina", "hábitos", "éxito", "investigación"],
    tema: "mentalidad",
  },
  {
    id: "podcast-joe-risser-mental-toughness",
    title: "The Secrets and Science of Mental Toughness",
    author: "Joe Risser MD, MPH (TEDxSanDiego)",
    description: "TEDx sobre la psicología y ciencia detrás de la fortaleza mental, explorando cómo desarrollar resiliencia y resistencia emocional.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/rNxC16mlO60",
    tags: ["fortaleza mental", "resiliencia", "psicología", "ciencia"],
    tema: "mentalidad",
  },
  {
    id: "podcast-romuald-fons-cobrar-caro",
    title: "Si no te atreves a cobrar más caro, mira esto",
    author: "Romuald Fons",
    description: "Romuald Fons comparte estrategias y mentalidad para romper las barreras que impiden cobrar precios más altos por tus servicios o productos.",
    type: "podcast",
    category: "marketing",
    status: "en-cola",
    url: "https://youtu.be/JXFifsK_ilA",
    tags: ["precios", "ventas", "marketing", "mentalidad"],
    tema: "marketing",
  },
  {
    id: "podcast-lama-rinchen-logros",
    title: "¿Quién eres sin tus logros? - Perlas de Sabiduría 5",
    author: "Lama Rinchen",
    description: "Reflexión profunda sobre la identidad más allá de los logros materiales y profesionales. ¿Quiénes somos cuando desprendemos nuestros éxitos?",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/2QR2v_11GLE",
    tags: ["identidad", "logros", "sabiduría", "espiritualidad"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-sadhguru-karma-devocion",
    title: "Karma, Iluminación y Devoción: Lo Que Realmente Significa Ser Devoto",
    author: "Sadhguru",
    description: "Sadhguru explora conceptos espirituales fundamentales como el karma, la iluminación y el verdadero significado de la devoción.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/41lzP_AxoBc",
    tags: ["karma", "iluminación", "devoción", "espiritualidad"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-simon-squibb-confidence",
    title: "Give Me 39 Minutes And I'll Make you Dangerously Confident",
    author: "Simon Squibb",
    description: "Simon Squibb presenta en 39 minutos los principios y ejercicios prácticos para desarrollar una confianza profunda y duradera.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/cJBwBR_WHcE",
    tags: ["confianza", "seguridad", "desarrollo personal", "mentalidad"],
    tema: "mentalidad",
  },
  {
    id: "podcast-hormozi-diary-ceo-millionaires",
    title: "The Man That Makes Millionaires: How To Turn $1,000 Into $100 Million! | Alex Hormozi",
    author: "The Diary Of A CEO",
    description: "Alex Hormozi revela en The Diary of a CEO las estrategias exactas para convertir $1,000 en $100 millones. Una masterclass de negocios y escalamiento.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/x3e73Qn6NOo",
    tags: ["negocios", "escalamiento", "millonario", "emprendimiento"],
    tema: "negocios",
  },
  {
    id: "podcast-hormozi-wealth-2026",
    title: "If You Want To Create Wealth In 2026, Watch This (4 Paths)",
    author: "Alex Hormozi",
    description: "Alex Hormozi presenta cuatro caminos concretos para generar riqueza en 2026, con estrategias probadas para construir ingresos significativos.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/sL16tsGafcQ",
    tags: ["riqueza", "finanzas", "estrategia", "ingresos"],
    tema: "dinero",
  },
  {
    id: "podcast-jefferson-fisher-gaslighting",
    title: "The Gaslighting Expert Jefferson Fisher: If They Do This, You're Being Manipulated!",
    author: "The Diary Of A CEO",
    description: "El experto en comunicación Jefferson Fisher revela las señales del gaslighting y cómo identificar y responder ante la manipulación psicológica.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/ZPVdK9v0CK8",
    tags: ["gaslighting", "manipulación", "psicología", "comunicación"],
    tema: "mentalidad",
  },
  {
    id: "podcast-stanford-dreams-brain",
    title: "Stanford Neuroscientist: Can't Remember Your Dreams? Your Brain May Be Warning You!",
    author: "The Diary Of A CEO",
    description: "Un neurocientífico de Stanford explica qué significa no recordar tus sueños y las señales que el cerebro puede estar enviando sobre tu salud mental y física.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/m-nnyNZ0TQ0",
    tags: ["sueños", "neurociencia", "cerebro", "salud mental"],
    tema: "mentalidad",
  },
  {
    id: "podcast-sadhguru-matriz-mente",
    title: "¿Atrapado en la matriz de tu mente?",
    author: "Sadhguru Español",
    description: "Sadhguru explora cómo la mente puede convertirse en una prisión y cómo liberarse de los patrones mentales que nos limitan.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/C6kwxVp3ku4",
    tags: ["mente", "consciencia", "espiritualidad", "liberación"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-cathie-wood-invest-2030",
    title: "Invest in This – It'll Be Worth $1.5 Million by 2030 | Cathie Wood",
    author: "The Diary Of A CEO",
    description: "La experta inversora Cathie Wood revela en qué invertir ahora para alcanzar $1.5 millones en 2030, con su visión sobre los mercados y tecnologías disruptivas.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/ZznpMh0DegE",
    tags: ["inversión", "riqueza", "finanzas", "mercados"],
    tema: "dinero",
  },
  {
    id: "podcast-hormozi-robbins-unlock-potential",
    title: "How to Unlock Your Potential",
    author: "Oculto (Alex Hormozi y Tony Robbins)",
    description: "Conversación entre Alex Hormozi y Tony Robbins sobre cómo desbloquear tu potencial y alcanzar el máximo nivel en negocios y vida personal.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/xz-ymFOhBAE",
    tags: ["potencial", "mentalidad", "Tony Robbins", "Alex Hormozi"],
    tema: "mentalidad",
  },
  {
    id: "podcast-sadhguru-feliz-cualquier-situacion",
    title: "¿Es posible estar feliz en cualquier situación?",
    author: "Sadhguru Español",
    description: "Sadhguru reflexiona sobre la naturaleza de la felicidad y si es posible mantenerla independientemente de las circunstancias externas.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/pJ7r3gjG4U8",
    tags: ["felicidad", "bienestar", "espiritualidad", "consciencia"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-sadhguru-banarse-correctamente",
    title: "¿Te estás bañando de la forma correcta?",
    author: "Sadhguru Español",
    description: "Sadhguru comparte la perspectiva espiritual y de bienestar sobre una práctica cotidiana como el baño, y cómo hacerlo de forma consciente.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/Peykas_e174",
    tags: ["bienestar", "hábitos", "consciencia", "espiritualidad"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-sadhguru-ser-mas-estable",
    title: "¿Cómo ser más estable?",
    author: "Sadhguru Español",
    description: "Sadhguru ofrece su perspectiva sobre cómo cultivar la estabilidad interior ante los cambios y turbulencias de la vida.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/IhHigllPHVc",
    tags: ["estabilidad", "equilibrio", "consciencia", "espiritualidad"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-lao-tse-tao-te-king",
    title: "Lao Tse — Tao Te King: Filosofía Taoísta",
    author: "MARTE 19",
    description: "Exploración profunda del Tao Te King de Lao Tse y los principios fundamentales del Taoísmo como guía de vida y sabiduría ancestral.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/xRBsNZqogno",
    tags: ["taoísmo", "Lao Tse", "filosofía", "sabiduría antigua"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-jordan-peterson-10-reglas",
    title: "Trátate como si Importaras | Jordan Peterson: 10 Reglas para el Éxito en la Vida",
    author: "Evan en Español",
    description: "Las 10 reglas de Jordan Peterson para el éxito y la vida significativa, traducidas y presentadas en español con reflexiones profundas sobre el autorespeto.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/TZ6qGTwhvTc",
    tags: ["Jordan Peterson", "éxito", "reglas de vida", "autorespeto"],
    tema: "mentalidad",
  },
  {
    id: "podcast-millonarios-endeudan-cardone",
    title: "Por qué los Grandes Millonarios se Endeudan | Grant Cardone & Lewis Howes",
    author: "Greatness Clips - Español",
    description: "Grant Cardone y Lewis Howes explican la mentalidad y estrategia detrás de por qué los millonarios usan la deuda como herramienta para generar riqueza.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/PnXGbpdqQ-U",
    tags: ["deuda", "millonarios", "inversión", "riqueza"],
    tema: "dinero",
  },
  {
    id: "podcast-regla-10x-libros-emprendedores",
    title: "La Regla 10X — La Regla de Oro de los Negocios",
    author: "Libros para Emprendedores con Luis Ramos",
    description: "Resumen del libro La Regla 10X de Grant Cardone: la filosofía de multiplicar por 10 tus acciones y metas para alcanzar el éxito en los negocios.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/mA91pUc6sSk",
    tags: ["10X", "negocios", "Grant Cardone", "emprendimiento"],
    tema: "negocios",
  },
  {
    id: "podcast-matthew-hussey-sentirte-atractivo",
    title: "Haz Esto para Sentirte más Atractivo | Matthew Hussey & Lewis Howes",
    author: "Lewis Howes Español",
    description: "Matthew Hussey y Lewis Howes comparten las claves para desarrollar confianza, presencia y atractivo genuino en las relaciones personales.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/gp3VB6Yj93I",
    tags: ["confianza", "atractivo", "relaciones", "desarrollo personal"],
    tema: "mentalidad",
  },
  {
    id: "podcast-wayne-dyer-soluciones-espirituales",
    title: "Soluciones Espirituales — Dr. Wayne Dyer",
    author: "Ley de Atracción y Abundancia",
    description: "El Dr. Wayne Dyer comparte soluciones espirituales a los desafíos cotidianos, conectando la consciencia interior con la transformación de la realidad exterior.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/_nC8anINNJk",
    tags: ["Wayne Dyer", "espiritualidad", "consciencia", "abundancia"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-vendedor-mas-grande-mundo",
    title: "El Vendedor Más Grande del Mundo — Resumen",
    author: "Libros para Emprendedores con Luis Ramos",
    description: "Resumen del clásico de Og Mandino sobre los principios atemporales de ventas, persistencia y éxito a través de hábitos y actitud mental positiva.",
    type: "podcast",
    category: "ventas",
    status: "en-cola",
    url: "https://youtu.be/eXZyFZoLUks",
    tags: ["ventas", "Og Mandino", "persistencia", "hábitos"],
    tema: "negocios",
  },
  {
    id: "podcast-joe-dispenza-abundancia-dinero",
    title: "Abundancia: Estrategias Infalibles para Atraer Dinero | Joe Dispenza",
    author: "Evan en Español",
    description: "Joe Dispenza comparte estrategias basadas en neurociencia y espiritualidad para reprogramar la mente y atraer abundancia y prosperidad económica.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/UaEvNoYkxu8",
    tags: ["abundancia", "dinero", "Joe Dispenza", "manifestación"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-charles-duhigg-persona-magnetica",
    title: "Domina el Arte de la Influencia: Cómo Ser una Persona Magnética | Charles Duhigg",
    author: "Lewis Howes Español",
    description: "Charles Duhigg revela los principios de la comunicación poderosa y cómo desarrollar una presencia magnética que influye y conecta profundamente con otros.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/40SgfUWBMMY",
    tags: ["influencia", "comunicación", "magnetismo", "carisma"],
    tema: "mentalidad",
  },
  {
    id: "podcast-robin-sharma-dar-vida-ideas",
    title: "Cómo Dar Vida a Tus Ideas Más Brillantes | Robin Sharma",
    author: "Greatness Clips - Español",
    description: "Robin Sharma comparte su método para convertir ideas poderosas en realidad, desarrollando la disciplina creativa y la ejecución con excelencia.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/mol5Rpxi9rY",
    tags: ["creatividad", "ideas", "Robin Sharma", "ejecución"],
    tema: "mentalidad",
  },
  {
    id: "podcast-jung-lado-oscuro-verdadero-yo",
    title: "Enfrenta tu Lado Oscuro, Conviértete en tu Verdadero Yo | Carl Jung",
    author: "FILOSOFÍAS DE VIDA",
    description: "Exploración de la psicología de Carl Jung sobre la sombra y cómo integrar el lado oscuro de la personalidad para alcanzar la individuación y el verdadero yo.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/RmWv4sDjHik",
    tags: ["Carl Jung", "sombra", "psicología", "autoconocimiento"],
    tema: "mentalidad",
  },
  {
    id: "podcast-tengo-un-plan-confianza",
    title: "3 Claves para Aumentar (Rápido) tu Confianza en ti Mismo",
    author: "Tengo un Plan",
    description: "Tres estrategias prácticas y accionables para desarrollar la confianza en uno mismo de forma rápida y sostenida.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/NnpcrIswiVw",
    tags: ["confianza", "autoestima", "desarrollo personal", "mentalidad"],
    tema: "mentalidad",
  },
  {
    id: "podcast-victor-kuppers-poder-actitud",
    title: "El Poder de la Actitud | Victor Küppers",
    author: "Claudio Olalla",
    description: "Victor Küppers explica con humor y profundidad por qué la actitud es el factor diferencial más poderoso en la vida personal y profesional, y cómo cultivarla conscientemente.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/_SNufDCmkC8",
    tags: ["Victor Küppers", "actitud", "motivación", "desarrollo personal"],
    tema: "mentalidad",
  },
  {
    id: "podcast-jim-rohn-superar-momentos-dificiles",
    title: "Cómo Superar los Momentos Difíciles | Seminario de Jim Rohn",
    author: "Empresario Tips",
    description: "Seminario en español de Jim Rohn donde comparte su filosofía para atravesar la adversidad, desarrollar resiliencia y convertir los momentos difíciles en trampolín hacia el éxito.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/0A131KY8avk",
    tags: ["Jim Rohn", "adversidad", "resiliencia", "éxito", "seminario"],
    tema: "mentalidad",
  },
  {
    id: "podcast-napoleon-hill-burlando-diablo",
    title: "Burlando al Diablo | Audiolibro — Napoleón Hill",
    author: "Napoleón Hill",
    description: "Audiolibro del clásico de Napoleón Hill de 1938, donde revela en forma de diálogo los secretos para superar el miedo, el fracaso y las fuerzas que limitan el éxito humano.",
    type: "audiolibro",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/DVGbmCJsZ4U",
    tags: ["Napoleón Hill", "audiolibro", "miedo", "éxito"],
    tema: "mentalidad",
  },
  {
    id: "podcast-rick-rubin-desbloquear-mente-creativa",
    title: "Cómo Desbloquear tu Mente Creativa | Rick Rubin & Lewis Howes",
    author: "Lewis Howes Español",
    description: "Rick Rubin y Lewis Howes conversan sobre los bloqueos creativos, cómo encontrar inspiración genuina y los principios que definen a los artistas y creadores más influyentes del mundo.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/P-biYow24ss",
    tags: ["Rick Rubin", "creatividad", "mente creativa", "Lewis Howes"],
    tema: "mentalidad",
  },
  {
    id: "audiolibro-rick-rubin-acto-de-crear",
    title: "El Acto de Crear | Audiolibro Completo — Rick Rubin",
    author: "GONZOWAV",
    description: "Audiolibro completo de 'The Creative Act' de Rick Rubin: una guía profunda sobre el proceso creativo, la inspiración y cómo conectar con la creatividad en cualquier disciplina.",
    type: "audiolibro",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/0iOTQcVY6Qs",
    tags: ["Rick Rubin", "creatividad", "arte", "proceso creativo"],
  },
  {
    id: "podcast-lordconstruye-42-anos-experiencia-dinero",
    title: "42 Años de Experiencia Sobre el Dinero en 28 Minutos",
    author: "LordConstruye",
    description: "Reflexiones densas y prácticas sobre finanzas personales, gestión del dinero y mentalidad de riqueza destiladas de más de cuatro décadas de experiencia.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/VD6shdAmegM",
    tags: ["dinero", "finanzas", "experiencia", "riqueza", "LordConstruye"],
    tema: "dinero",
  },
  {
    id: "documental-history-como-se-fabrica-el-poder-trump",
    title: "Cómo se Fabrica el PODER — El Método Trump",
    author: "Canal pendiente de confirmar",
    description: "Análisis sobre los mecanismos de construcción del poder político y empresarial a través del caso de Donald Trump.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/EL5RlIzRfgA",
    tags: ["Trump", "poder", "liderazgo", "negocios"],
    tema: "negocios",
  },
  {
    id: "documental-inexplicable-clarividencia",
    title: "IneXplicable | Clarividencia: El Poder que Todos Tenemos",
    author: "History Latinoamérica",
    description: "Versión extendida sin cortes del episodio sobre clarividencia del documental IneXplicable de History Channel: investigaciones, casos reales y la ciencia detrás de esta capacidad humana.",
    type: "documental",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/HcKWsT6hl8I",
    tags: ["clarividencia", "documental", "History Channel", "paranormal", "conciencia"],
  },
  {
    id: "podcast-trump-tecnicas-negociacion-miralles",
    title: "10 Técnicas de Negociación de Donald Trump para Ganar Siempre",
    author: "Fernando Miralles",
    description: "Fernando Miralles analiza las 10 tácticas de negociación que Donald Trump ha aplicado en sus grandes acuerdos empresariales y cómo adaptarlas para ganar en cualquier negociación.",
    type: "podcast",
    category: "ventas",
    status: "en-cola",
    url: "https://youtu.be/OydnqH-gbXA",
    tags: ["negociación", "Trump", "ventas", "técnicas", "Fernando Miralles"],
    tema: "negocios",
  },
  {
    id: "podcast-bob-proctor-ley-vibracion",
    title: "Bob Proctor: La Ley de la Vibración Explicada (Manifiesta Cualquier Cosa Rápidamente)",
    author: "Lewis Howes Español",
    description: "Bob Proctor explica la ley de la vibración y cómo alinear tu energía mental y emocional para manifestar resultados concretos en cualquier área de tu vida.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/EblGM-sJ7zk",
    tags: ["Bob Proctor", "vibración", "manifestación", "ley de atracción"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-harvey-mackay-esencia-liderazgo",
    title: "La Esencia del Liderazgo: Lecciones de Harvey Mackay",
    author: "LIDERAZGO PODEROSO",
    description: "Harvey Mackay comparte las lecciones fundamentales de liderazgo que definen a los grandes líderes: cómo inspirar equipos, tomar decisiones difíciles y dejar un legado.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/5lKjg2KaYSA",
    tags: ["Harvey Mackay", "liderazgo", "equipos", "negocios"],
    tema: "negocios",
  },
  {
    id: "podcast-lisa-ford-perspectiva-cliente",
    title: "Perspectiva del Cliente: Transformando tu Negocio | Lisa Ford",
    author: "LIDERAZGO PODEROSO",
    description: "Lisa Ford revela cómo ver el negocio desde la perspectiva del cliente para transformar la experiencia, fidelizar y diferenciarse en un mercado competitivo.",
    type: "podcast",
    category: "ventas",
    status: "en-cola",
    url: "https://youtu.be/lOefN6a_Vjo",
    tags: ["cliente", "experiencia", "Lisa Ford", "servicio", "negocio"],
    tema: "negocios",
  },
  {
    id: "podcast-terapia-conductual-regla-hawking-inquebrantable",
    title: "Experto en Terapia Conductual Revela la Regla de Hawking que te Vuelve Inquebrantable",
    author: "La Fórmula Podcast por Mili Hadad",
    description: "Un experto en terapia conductual explica la regla de Hawking y cómo aplicarla para desarrollar una resiliencia mental a prueba de cualquier adversidad.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/eBiDtFZURAc",
    tags: ["resiliencia", "terapia conductual", "Hawking", "mentalidad", "psicología"],
    tema: "mentalidad",
  },
  {
    id: "podcast-blink-gladwell-analisis-conocimiento-experto",
    title: "Blink: Inteligencia Intuitiva para la Toma de Decisiones | Análisis — Malcolm Gladwell",
    author: "Conocimiento Experto",
    description: "Análisis profundo del libro 'Blink' de Malcolm Gladwell: cómo el inconsciente toma decisiones brillantes en segundos y en qué situaciones debemos —o no— confiar en ese instinto.",
    type: "podcast",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/2o6rTyI3v3c",
    tags: ["Malcolm Gladwell", "Blink", "intuición", "decisiones", "psicología"],
    tema: "mentalidad",
  },
  {
    id: "audiolibro-malcolm-gladwell-inteligencia-intuitiva",
    title: "Inteligencia Intuitiva | Audiolibro — Malcolm Gladwell",
    author: "OwlCast",
    description: "Audiolibro de 'Blink' de Malcolm Gladwell sobre el poder del pensamiento inconsciente: cómo la mente toma decisiones rápidas e intuitivas y cuándo confiar en ellas.",
    type: "audiolibro",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/WeTeJ5YrQds",
    tags: ["Malcolm Gladwell", "intuición", "decisiones", "psicología", "Blink"],
  },
  {
    id: "podcast-amy-cuddy-lenguaje-corporal",
    title: "Tu Lenguaje Corporal Moldea Quién Eres | Amy Cuddy",
    author: "Estrategias De Aprendizaje",
    description: "Amy Cuddy explica cómo la postura y el lenguaje no verbal no solo comunican cómo nos sentimos, sino que moldean activamente nuestra confianza, identidad y rendimiento.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/DMORde1RWEk",
    tags: ["Amy Cuddy", "lenguaje corporal", "confianza", "postura", "TED"],
    tema: "mentalidad",
  },
  {
    id: "podcast-isra-bravo-copywriter-magistral",
    title: "Isra Bravo: El Copywriter Más Cotizado en Español | Magistral",
    author: "MAGISTRAL",
    description: "Entrevista a Isra Bravo, referente del copywriting en español, donde comparte su filosofía de escritura persuasiva, cómo construyó su reputación y sus principios para vender con palabras.",
    type: "podcast",
    category: "marketing",
    status: "en-cola",
    url: "https://youtu.be/RpeBlqeMMRM",
    tags: ["copywriting", "Isra Bravo", "escritura persuasiva", "marketing"],
    tema: "marketing",
  },
  {
    id: "podcast-rosser-herramientas-linguisticas-camareros",
    title: "Herramientas Lingüísticas Proactivas para Camareros | Eduardo Rosser",
    author: "Abrasador Del Campo a la Parrilla",
    description: "Eduardo Rosser presenta técnicas de comunicación y lenguaje proactivo para profesionales de sala, orientadas a mejorar la experiencia del cliente y aumentar las ventas.",
    type: "podcast",
    category: "ventas",
    status: "en-cola",
    url: "https://www.youtube.com/watch?v=eey_-3DmbqY",
    tags: ["comunicación", "hostelería", "ventas", "lenguaje", "camareros"],
    tema: "negocios",
  },
  {
    id: "audiolibro-brian-tracy-tragese-el-sapo",
    title: "Trágese ese Sapo | Audiolibro — Brian Tracy",
    author: "EL PODER DE LOS HÁBITOS",
    description: "Audiolibro del clásico de Brian Tracy sobre cómo vencer la procrastinación y ejecutar las tareas más importantes primero para maximizar la productividad.",
    type: "audiolibro",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/90ocH6zaqcI",
    tags: ["Brian Tracy", "productividad", "procrastinación", "hábitos"],
  },
  {
    id: "podcast-alex-hormozi-tan-rico",
    title: "Cómo Volverse TAN Rico que te Cuestiones el Sentido de Ganar Dinero",
    author: "Alex Hormozi en Español",
    description: "Alex Hormozi reflexiona sobre qué sucede cuando acumulas riqueza suficiente y cómo replantear el propósito del dinero más allá de la acumulación.",
    type: "podcast",
    category: "finanzas",
    status: "en-cola",
    url: "https://youtu.be/ac9UfBBR-TU",
    tags: ["Alex Hormozi", "riqueza", "dinero", "propósito"],
    tema: "dinero",
  },
  {
    id: "podcast-raimond-torrents-secretos-persuasion",
    title: "Los Secretos de la Persuasión | Raimond Torrents | TEDxSitges",
    author: "TEDx Talks",
    description: "Charla TEDx de Raimond Torrents donde revela los principios psicológicos de la persuasión y cómo aplicarlos éticamente para influir y comunicar con mayor impacto.",
    type: "podcast",
    category: "marketing",
    status: "en-cola",
    url: "https://youtu.be/VpllBH46vF0",
    tags: ["persuasión", "TED", "influencia", "comunicación"],
    tema: "marketing",
  },
  {
    id: "documental-freddie-mercury-leyenda",
    title: "¿Por Qué se Convirtió en Leyenda? | Freddie Mercury | Documental",
    author: "Dieck Docs",
    description: "Documental que explora los factores que convirtieron a Freddie Mercury en una leyenda inmortal de la música: su talento único, su presencia escénica y su impacto cultural.",
    type: "documental",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/E1cwCdRQL5E",
    tags: ["Freddie Mercury", "Queen", "documental", "biografía", "música"],
  },
  {
    id: "podcast-sinek-lideres-inspiran-accion",
    title: "Cómo los Grandes Líderes Inspiran la Acción | Simon Sinek",
    author: "Fundación Ideas para la Paz",
    description: "La famosa charla de Simon Sinek sobre el Golden Circle y por qué los líderes e innovadores que inspiran comienzan siempre con el 'porqué'.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/4bcB5FJq80Q",
    tags: ["Simon Sinek", "liderazgo", "inspiración", "Golden Circle"],
    tema: "negocios",
  },
  {
    id: "podcast-riqueza-practica-manifestar-riqueza",
    title: "Aprende a Manifestar, Atrae la Riqueza | Joseph Murphy, Neville Goddard, Tesla",
    author: "Riqueza Práctica",
    description: "Compilación de enseñanzas sobre manifestación y atracción de riqueza de Joseph Murphy, Conny Méndez, Neville Goddard y Nikola Tesla.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/6sSe8uZ5MuE",
    tags: ["manifestación", "riqueza", "Joseph Murphy", "Neville Goddard", "ley de atracción"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-marisa-peer-nino-interior",
    title: "Cómo Sanar tu Niño Interior | Marisa Peer",
    author: "Greatness Clips - Español",
    description: "Marisa Peer explica cómo identificar y sanar las heridas del niño interior para liberar patrones limitantes y alcanzar una vida plena.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/rvseX2eoIVc",
    tags: ["niño interior", "sanación", "Marisa Peer", "psicología"],
    tema: "espiritualidad",
  },
  {
    id: "podcast-xavier-pirla-como-vender-mejor",
    title: "Cómo Vender Mejor | Superar el Miedo a Vender",
    author: "Xavier Pirla | Influencia y Persuasión Consciente",
    description: "Conferencia práctica sobre técnicas de ventas y cómo superar los bloqueos emocionales que impiden vender con confianza y autenticidad.",
    type: "podcast",
    category: "ventas",
    status: "en-cola",
    url: "https://youtu.be/PLIeEpakWig",
    tags: ["ventas", "persuasión", "miedo", "influencia"],
    tema: "negocios",
  },
  {
    id: "podcast-ia-jornadas-usos-practicos",
    title: "Jornadas de la IA: Usos Prácticos de la Inteligencia Artificial",
    author: "Inteligencia Artificial",
    description: "Presentación sobre aplicaciones prácticas y casos de uso reales de la inteligencia artificial para negocios y productividad.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://www.youtube.com/live/KBcC6tQJ2fI",
    tags: ["inteligencia artificial", "IA", "productividad", "tecnología"],
    tema: "negocios",
  },
  {
    id: "podcast-mario-alonso-puig-comunicacion-asertiva",
    title: "La Diferencia entre Hablar y Comunicar | Comunicación Asertiva",
    author: "Mario Alonso Puig - Oficial",
    description: "Mario Alonso Puig revela los principios de la comunicación asertiva y cómo la forma en que nos expresamos transforma nuestras relaciones y resultados.",
    type: "podcast",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/kLPmJbeLAE8",
    tags: ["comunicación", "asertividad", "Mario Alonso Puig", "liderazgo"],
    tema: "desarrollo-personal",
  },
  {
    id: "audiolibro-simon-sinek-empieza-con-el-porque",
    title: "Empieza con el Porqué | Audiolibro — Simon Sinek",
    author: "Conocimiento Experto",
    description: "Análisis del bestseller de Simon Sinek sobre cómo los líderes e innovadores que inspiran parten siempre de un propósito claro: el Golden Circle.",
    type: "audiolibro",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/7PXWXpDzJBc",
    tags: ["Simon Sinek", "propósito", "liderazgo", "innovación"],
  },
  {
    id: "audiolibro-kahneman-pensar-rapido-despacio",
    title: "Pensar Rápido, Pensar Despacio | Audiolibro — Daniel Kahneman",
    author: "SlavojZizekEspaño-libros",
    description: "Audiolibro del clásico de Daniel Kahneman sobre los dos sistemas de pensamiento que guían nuestras decisiones: el rápido e intuitivo y el lento y racional.",
    type: "audiolibro",
    category: "psicologia",
    status: "en-cola",
    url: "https://youtu.be/RVccLP9Jrq8",
    tags: ["Daniel Kahneman", "psicología cognitiva", "decisiones", "sesgos"],
  },
  {
    id: "podcast-sadhguru-extinction-prediction",
    title: "Sadhguru PREDICTION: Why We Are Now On 'The Brink Of Extinction'",
    author: "Sadhguru",
    description: "Sadhguru comparte su visión sobre el estado crítico de la humanidad y por qué nos encontramos en un momento de inflexión existencial.",
    type: "podcast",
    category: "espiritualidad",
    status: "en-cola",
    url: "https://youtu.be/PACpvHgJ9HM",
    tags: ["humanidad", "consciencia", "espiritualidad", "futuro"],
    tema: "espiritualidad",
  },
  {
    id: "audiolibro-como-argumentar-como-abogado",
    title: "Cómo Argumentar Como un Abogado (y Ganar) — Audiolibro",
    author: "Qvibe & Despertar",
    description: "Audiolibro que enseña las técnicas de argumentación y razonamiento lógico que usan los abogados para construir casos sólidos y persuadir con evidencia.",
    type: "audiolibro",
    category: "desarrollo-personal",
    status: "en-cola",
    url: "https://youtu.be/JKSR_DWO3nA",
    tags: ["argumentación", "persuasión", "comunicación", "lógica"],
  },
  {
    id: "podcast-regla-10x-grant-cardone",
    title: "La Regla 10X — La Regla de Oro de los Negocios",
    author: "Libros para Emprendedores con Luis Ramos",
    description: "Resumen del libro de Grant Cardone: la filosofía de multiplicar por 10 tus metas y acciones para alcanzar el éxito extraordinario en los negocios.",
    type: "podcast",
    category: "negocios",
    status: "en-cola",
    url: "https://youtu.be/mA91pUc6sSk",
    tags: ["Grant Cardone", "10X", "emprendimiento", "metas", "negocios"],
    tema: "negocios",
  },
  {
    id: "youtube-magistral-entrevistas",
    title: "MAGISTRAL",
    author: "MagistralEntrevistas",
    description: "Entrevistas en profundidad con referentes del marketing, copywriting, ventas y emprendimiento en español.",
    type: "youtube",
    category: "marketing",
    status: "en-cola",
    url: "https://www.youtube.com/@MagistralEntrevistas",
    tags: ["entrevistas", "copywriting", "marketing", "ventas", "emprendimiento"],
  },
];
